### Import modules

In [1]:
import pandas as pd
import os
import numpy as np
import matplotlib.pyplot as plt

### Load dataset

In [164]:
# searching files
all_files = os.listdir('af_data')

In [165]:
# combining info from all files into one dataframe
data = None

for f in all_files:
    data_f = pd.read_csv(f'af_data/{f}', sep=';')
    
    if data is None:
        data = data_f.copy()
        continue
    
    data = data.append(data_f, ignore_index=True)

### Data understanding

In [166]:
# checking first 5 rows
data.head()

,ДатаЧека,НомерЧека,ВидОперации,АЗСКод,ВидНоменклатуры,Карта,ОсновнаяКарта,НомерСтроки,НоменклатураКод,Количество,Цена,Сумма,Бонусы,СуммаСкидки,УниверсальнаяАкцияКод,СписаноБонусов,СуммаСкидкиДисконт,КассоваяСмена,ОператорКод,Unnamed: 19
0,16.12.2019 00:09:30,26171000011408,Начисление,2617,Нефтепродукты,F9CF1DC89C51CEC7AADC699E41D3B5FA,NaN,1,145236,"10,35","28,99",300,1 552,"0,05",NaN,0,0,af656c5c-1f86-11ea-931b-00012eb1adb5,Федів Ірина Василівна,NaN
1,16.12.2019 00:09:34,37151000009864,Начисление,3715,Сопутка,47A4505237411EDFCF7FB7352D871839,NaN,1,136788,2,37,74,74,0,NaN,0,0,1b2cac5c-1f87-11ea-b05b-00012eb1a3ee,Буднік Олексій Геннадійович,NaN
2,16.12.2019 00:11:14,35081000014146,Начисление,3508,Сопутка,7BE05F497977C0DE8903D25EBC664D3A,NaN,1,210952,1,48,48,0,0,NaN,0,0,a2937477-1f86-11ea-9b3a-00012eb19bcf,Турусова Анастасія Володимирівна,NaN
3,16.12.2019 00:11:14,35081000014146,Начисление,3508,Сопутка,7BE05F497977C0DE8903D25EBC664D3A,NaN,2,232064,1,26,26,0,0,NaN,0,0,a2937477-1f86-11ea-9b3a-00012eb19bcf,Турусова Анастасія Володимирівна,NaN
4,16.12.2019 00:11:14,35081000014146,Начисление,3508,Сопутка,7BE05F497977C0DE8903D25EBC664D3A,NaN,3,232075,1,28,28,0,0,NaN,0,0,a2937477-1f86-11ea-9b3a-00012eb19bcf,Турусова Анастасія Володимирівна,NaN

In [167]:
# info about dataframe
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 91903 entries, 0 to 91902
Data columns (total 20 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   ДатаЧека               91903 non-null  object
 1   НомерЧека              91903 non-null  int64
 2   ВидОперации            91903 non-null  object
 3   АЗСКод                 91903 non-null  int64
 4   ВидНоменклатуры        91903 non-null  object
 5   Карта                  91901 non-null  object
 6   ОсновнаяКарта          127 non-null    object
 7   НомерСтроки            91903 non-null  int64
 8   НоменклатураКод        91903 non-null  int64
 9   Количество             91903 non-null  object
 10  Цена                   91903 non-null  object
 11  Сумма                  91903 non-null  object
 12  Бонусы                 91903 non-null  object
 13  СуммаСкидки            91903 non-null  object
 14  УниверсальнаяАкцияКод  11445 non-null  float64
 15  СписаноБонусов         91903 non-null  object
 16  СуммаСкидкиДисконт     91903 non-null  int64
 17  КассоваяСмена          91903 non-null  object
 18  ОператорКод            91873 non-null  object
 19  Unnamed: 19            0 non-null      float64
dtypes: float64(2), int64(5), object(13)
memory usage: 14.0+ MB

In [ ]:
# adding labels

In [6]:
data['label'] = 0

In [168]:
labels = pd.read_csv('other_data/card_69.csv').values

In [85]:
for i in labels:
    data.loc[data['Карта'] == i[0], 'label'] = 1

In [169]:
fraud_list = []
for i in labels:
    fraud_list.append(i[0])

In [ ]:
# card data

In [ ]:
# card_data = data.groupby('Карта').count()

In [ ]:
# card_data = card_data.rename(columns={'ДатаЧека':'operations_per_30days'})

In [190]:
final_card_data['is_fraud'] = 0

In [ ]:
# card_data = card_data[['operations_per_30days', 'is_fraud']]

In [192]:
for i, row in final_card_data.iterrows():
    if i in fraud_list:
        row['is_fraud'] = 1

In [98]:
data

,ДатаЧека,НомерЧека,ВидОперации,АЗСКод,ВидНоменклатуры,Карта,ОсновнаяКарта,НомерСтроки,НоменклатураКод,Количество,Цена,Сумма,Бонусы,СуммаСкидки,УниверсальнаяАкцияКод,СписаноБонусов,СуммаСкидкиДисконт,КассоваяСмена,ОператорКод
0,03.06.2020 00:20:26,26201000001094,Начисление,2620,Сопутка,71557CEEA393407549118FF4FA91EAB3,NaN,1,223154.0,1,44,44,44,0,NaN,0,0,54519072-a514-11ea-afbd-00012eb19ff4,Соболь Наталія Михайлівна
1,03.06.2020 00:20:26,26201000001094,Начисление,2620,Сопутка,71557CEEA393407549118FF4FA91EAB3,NaN,5,206150.0,2,"20,2","40,4",40,0,NaN,0,0,54519072-a514-11ea-afbd-00012eb19ff4,Соболь Наталія Михайлівна
2,03.06.2020 00:20:26,26201000001094,Начисление,2620,Сопутка,71557CEEA393407549118FF4FA91EAB3,NaN,8,198228.0,2,"51,9","103,8",0,0,NaN,0,0,54519072-a514-11ea-afbd-00012eb19ff4,Соболь Наталія Михайлівна
3,03.06.2020 00:20:26,26201000001094,Начисление,2620,Сопутка,71557CEEA393407549118FF4FA91EAB3,NaN,4,123226.0,1,30,30,30,0,NaN,0,0,54519072-a514-11ea-afbd-00012eb19ff4,Соболь Наталія Михайлівна
4,03.06.2020 00:20:26,26201000001094,Начисление,2620,Сопутка,71557CEEA393407549118FF4FA91EAB3,NaN,7,82907.0,2,"35,4","70,8",70,0,NaN,0,0,54519072-a514-11ea-afbd-00012eb19ff4,Соболь Наталія Михайлівна
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19477,04.05.2020 23:33:47,26191000003177,Начисление,2619,Сопутка,689ED62A15B3DE16398001B3A86FA9CF,NaN,4,232074.0,1,39,"31,2",0,"7,8",4882.0,0,0,93dbd6ea-8d81-11ea-9086-00012eb1ada8,Тиркот Х.А.
19478,04.05.2020 23:33:47,26191000003177,Начисление,2619,Сопутка,689ED62A15B3DE16398001B3A86FA9CF,NaN,1,234777.0,1,59,"47,2",0,"11,8",4882.0,0,0,93dbd6ea-8d81-11ea-9086-00012eb1ada8,Тиркот Х.А.
19479,04.05.2020 23:33:47,26191000003177,Начисление,2619,Сопутка,689ED62A15B3DE16398001B3A86FA9CF,NaN,2,244742.0,1,29,"23,2",0,"5,8",4882.0,0,0,93dbd6ea-8d81-11ea-9086-00012eb1ada8,Тиркот Х.А.
19480,04.05.2020 23:37:44,34224000001761,Начисление,3422,Сопутка,8E20214A15815D63DC795E02CBD78DED,NaN,1,255667.0,14,29,"365,4",0,"40,6",4881.0,0,0,0ecfc5f5-8d82-11ea-95ed-00012eb194d9,Булименко Тетяна Миколаївна
19481,04.05.2020 23:41:58,16461000001878,Начисление оплата,1646,Сопутка,B1B3A892578C48C7723DC06F9F7ACE4B,NaN,1,214778.0,1,"15,9","0,01",0,"15,89",5199.0,1 113,0,08147650-8d82-11ea-8a21-00012eb1a3b4,Жалко Н.Б.

In [170]:
# converting string values to float
data['Количество'] = data['Количество'].apply(lambda x:float(x.replace('\xa0', '').replace(',', '.')))
data['Цена'] = data['Цена'].apply(lambda x:float(x.replace('\xa0', '').replace(',', '.')))
data['Сумма'] = data['Сумма'].apply(lambda x:float(x.replace('\xa0', '').replace(',', '.')))
data['Бонусы'] = data['Бонусы'].apply(lambda x:float(x.replace('\xa0', '').replace(',', '.')))
data['СуммаСкидки'] = data['СуммаСкидки'].apply(lambda x:float(x.replace('\xa0', '').replace(',', '.')))
data['СписаноБонусов'] = data['СписаноБонусов'].apply(lambda x:float(x.replace('\xa0', '').replace(',', '.')))

### Preparing and filtering data

In [171]:
# filtering rows
data = data[data['ВидОперации']!='Начисление возврат']
data = data[data['ВидОперации']!='Начисление оплата возврат']

In [172]:
# filtering rows
data = data[data['ВидНоменклатуры']=='Нефтепродукты']

# removing the column
# data = data.drop('ВидНоменклатуры', axis=1)

In [173]:
# remove other discounts
data['УниверсальнаяАкцияКод'] = data['УниверсальнаяАкцияКод'].fillna(0)
data = data[data['УниверсальнаяАкцияКод'] < 300]

In [174]:
# remove cards with more than 1 station
many_st = []
for i in set(data['Карта'].values):
    if len(set(data.loc[data['Карта']==i]['АЗСКод'].values)) > 1: 
        many_st.append(i)
        
for j in many_st:
    data = data[data['Карта'] != j]

In [175]:
# remove cards with less than 5 operations
card_data_lines = data.groupby('Карта').count()
delete_list = card_data_lines[card_data_lines['ДатаЧека']<5].index
for i in delete_list:
    data = data[data['Карта'] != i]

In [176]:
# leave only date withou time
data['ДатаЧека'] = data['ДатаЧека'].apply(lambda x: x.split(' ')[0])

In [177]:
data['ДатаЧека_m'] = data['ДатаЧека'].apply(lambda x: x.split('.')[1])

In [178]:
data.groupby('Карта').count()

,ДатаЧека,НомерЧека,ВидОперации,АЗСКод,ВидНоменклатуры,ОсновнаяКарта,НомерСтроки,НоменклатураКод,Количество,Цена,Сумма,Бонусы,СуммаСкидки,УниверсальнаяАкцияКод,СписаноБонусов,СуммаСкидкиДисконт,КассоваяСмена,ОператорКод,Unnamed: 19,ДатаЧека_m
Карта,,,,,,,,,,,,,,,,,,,,
002043206DC69131FC6444B0880F2D07,6,6,6,6,6,0,6,6,6,6,6,6,6,6,6,6,6,6,0,6
0049F1FFC58BD9977F50E56C71D5536B,12,12,12,12,12,0,12,12,12,12,12,12,12,12,12,12,12,12,0,12
005595BFFC7222DBB557E59A3872E56D,7,7,7,7,7,0,7,7,7,7,7,7,7,7,7,7,7,7,0,7
00DC9FCD81231002E2015CF04A2B01C2,11,11,11,11,11,0,11,11,11,11,11,11,11,11,11,11,11,11,0,11
00EB869662094C3C148EAEB8672D2BB7,8,8,8,8,8,0,8,8,8,8,8,8,8,8,8,8,8,8,0,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
FF88E8952CBA6FF330B9DF3F6CA6F2DA,5,5,5,5,5,0,5,5,5,5,5,5,5,5,5,5,5,5,0,5
FFB1A367E4B62FB268767E712E404986,5,5,5,5,5,0,5,5,5,5,5,5,5,5,5,5,5,5,0,5
FFD689128D88650F6820A54E3604DD09,5,5,5,5,5,0,5,5,5,5,5,5,5,5,5,5,5,5,0,5
FFD8567FF1048ABD2B486C2D08FE3B34,9,9,9,9,9,0,9,9,9,9,9,9,9,9,9,9,9,9,0,9
FFDDE5951E14CA31FA92F14FDF88CFB1,8,8,8,8,8,0,8,8,8,8,8,8,8,8,8,8,8,8,0,8

In [179]:
card_data = data.groupby('Карта').count()

In [180]:
operations_per_day = []
operations_per_month = []
for i in card_data.index:
    i_data = data[data['Карта'] == i]
    max_day = max(i_data.groupby('ДатаЧека').count()['НомерЧека'])
    max_mon = max(i_data.groupby('ДатаЧека_m').count()['НомерЧека'])
    len_oper = len(i_data)
    len_d = len(set(i_data['ДатаЧека']))
    len_m = len(set(i_data['ДатаЧека_m']))
    mean_day = len_oper/len_d
    mean_mon = len_oper/len_m
    operations_per_day.append(round(max_day/mean_day, 2))
    operations_per_month.append(round(max_mon/mean_mon, 2))

In [181]:
card_data['operations_per_day'] = operations_per_day
card_data['operations_per_month'] = operations_per_month

In [182]:
card_data

,ДатаЧека,НомерЧека,ВидОперации,АЗСКод,ВидНоменклатуры,ОсновнаяКарта,НомерСтроки,НоменклатураКод,Количество,Цена,...,СуммаСкидки,УниверсальнаяАкцияКод,СписаноБонусов,СуммаСкидкиДисконт,КассоваяСмена,ОператорКод,Unnamed: 19,ДатаЧека_m,operations_per_day,operations_per_month
Карта,,,,,,,,,,,,,,,,,,,,,
002043206DC69131FC6444B0880F2D07,6,6,6,6,6,0,6,6,6,6,...,6,6,6,6,6,6,0,6,1.00,1.0
0049F1FFC58BD9977F50E56C71D5536B,12,12,12,12,12,0,12,12,12,12,...,12,12,12,12,12,12,0,12,1.50,1.0
005595BFFC7222DBB557E59A3872E56D,7,7,7,7,7,0,7,7,7,7,...,7,7,7,7,7,7,0,7,1.71,1.0
00DC9FCD81231002E2015CF04A2B01C2,11,11,11,11,11,0,11,11,11,11,...,11,11,11,11,11,11,0,11,1.00,1.0
00EB869662094C3C148EAEB8672D2BB7,8,8,8,8,8,0,8,8,8,8,...,8,8,8,8,8,8,0,8,1.75,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
FF88E8952CBA6FF330B9DF3F6CA6F2DA,5,5,5,5,5,0,5,5,5,5,...,5,5,5,5,5,5,0,5,1.00,1.0
FFB1A367E4B62FB268767E712E404986,5,5,5,5,5,0,5,5,5,5,...,5,5,5,5,5,5,0,5,1.60,1.0
FFD689128D88650F6820A54E3604DD09,5,5,5,5,5,0,5,5,5,5,...,5,5,5,5,5,5,0,5,1.60,1.0
FFD8567FF1048ABD2B486C2D08FE3B34,9,9,9,9,9,0,9,9,9,9,...,9,9,9,9,9,9,0,9,1.78,1.0
FFDDE5951E14CA31FA92F14FDF88CFB1,8,8,8,8,8,0,8,8,8,8,...,8,8,8,8,8,8,0,8,1.00,1.0

In [41]:
card_data

,ДатаЧека,НомерЧека,ВидОперации,АЗСКод,ВидНоменклатуры,ОсновнаяКарта,НомерСтроки,НоменклатураКод,Количество,Цена,...,Бонусы,СуммаСкидки,УниверсальнаяАкцияКод,СписаноБонусов,СуммаСкидкиДисконт,КассоваяСмена,ОператорКод,ДатаЧека_m,operations_per_day,operations_per_month
Карта,,,,,,,,,,,,,,,,,,,,,
0357098A9B4792A725030975FF992E46,9,9,9,9,9,0,9,9,9,9,...,9,9,9,9,9,9,9,9,1.29,2.25
03A32DA0336671361C853C10B69E95AF,15,15,15,15,15,0,15,15,15,15,...,15,15,15,15,15,15,15,15,1.00,3.75
07D3E77CD24DA3154BA219D09BF93B4B,50,50,50,50,50,0,50,50,50,50,...,50,50,50,50,50,50,50,50,1.11,12.50
0847BF2B4784F83823D515D04C6D9639,6,6,6,6,6,0,6,6,6,6,...,6,6,6,6,6,6,6,6,1.00,1.50
0B1FF492733C3A08D34DE0D7424A2549,27,27,27,27,27,0,27,27,27,27,...,27,27,27,27,27,27,27,27,1.04,6.75
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
E762D39C0AD2B8E8F25FCF4652E65689,22,22,22,22,22,0,22,22,22,22,...,22,22,22,22,22,22,22,22,1.05,5.50
EAA77BE5D715CF896BEB26C0674F7024,23,23,23,23,23,0,23,23,23,23,...,23,23,23,23,23,23,23,23,1.21,5.75
EBF4E943181ADB99FEB3A30A7101562B,20,20,20,20,20,0,20,20,20,20,...,20,20,20,20,20,20,20,20,1.33,6.67
F125B1B2BBF74755ACA2537AAA209E7C,19,19,19,19,19,0,19,19,19,19,...,19,19,19,19,19,19,19,19,1.36,6.33
F5D40EB63F272F3425457352C9168C9F,14,14,14,14,14,0,14,14,14,14,...,14,14,14,14,14,14,14,14,1.00,3.50

In [ ]:
#TODO:
# date ?
# operators

In [18]:
card_data = data.groupby('Карта').count()

In [19]:
card_data

,ДатаЧека,НомерЧека,ВидОперации,АЗСКод,ВидНоменклатуры,ОсновнаяКарта,НомерСтроки,НоменклатураКод,Количество,Цена,Сумма,Бонусы,СуммаСкидки,УниверсальнаяАкцияКод,СписаноБонусов,СуммаСкидкиДисконт,КассоваяСмена,ОператорКод
Карта,,,,,,,,,,,,,,,,,,
0357098A9B4792A725030975FF992E46,9,9,9,9,9,0,9,9,9,9,9,9,9,9,9,9,9,9
03A32DA0336671361C853C10B69E95AF,15,15,15,15,15,0,15,15,15,15,15,15,15,15,15,15,15,15
07D3E77CD24DA3154BA219D09BF93B4B,50,50,50,50,50,0,50,50,50,50,50,50,50,50,50,50,50,50
0847BF2B4784F83823D515D04C6D9639,6,6,6,6,6,0,6,6,6,6,6,6,6,6,6,6,6,6
0B1FF492733C3A08D34DE0D7424A2549,27,27,27,27,27,0,27,27,27,27,27,27,27,27,27,27,27,27
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
E762D39C0AD2B8E8F25FCF4652E65689,22,22,22,22,22,0,22,22,22,22,22,22,22,22,22,22,22,22
EAA77BE5D715CF896BEB26C0674F7024,23,23,23,23,23,0,23,23,23,23,23,23,23,23,23,23,23,23
EBF4E943181ADB99FEB3A30A7101562B,20,20,20,20,20,0,20,20,20,20,20,20,20,20,20,20,20,20
F125B1B2BBF74755ACA2537AAA209E7C,19,19,19,19,19,0,19,19,19,19,19,19,19,19,19,19,19,19
F5D40EB63F272F3425457352C9168C9F,14,14,14,14,14,0,14,14,14,14,14,14,14,14,14,14,14,14

In [183]:
final_card_data = pd.DataFrame(card_data[['operations_per_day', 'operations_per_month']])

In [139]:
card_data = pd.DataFrame(card_data[['ДатаЧека', 'operations_per_day', 'operations_per_month']])

In [184]:
final_card_data

                                  operations_per_day  operations_per_month
Карта
002043206DC69131FC6444B0880F2D07                1.00                   1.0
0049F1FFC58BD9977F50E56C71D5536B                1.50                   1.0
005595BFFC7222DBB557E59A3872E56D                1.71                   1.0
00DC9FCD81231002E2015CF04A2B01C2                1.00                   1.0
00EB869662094C3C148EAEB8672D2BB7                1.75                   1.0
...                                              ...                   ...
FF88E8952CBA6FF330B9DF3F6CA6F2DA                1.00                   1.0
FFB1A367E4B62FB268767E712E404986                1.60                   1.0
FFD689128D88650F6820A54E3604DD09                1.60                   1.0
FFD8567FF1048ABD2B486C2D08FE3B34                1.78                   1.0
FFDDE5951E14CA31FA92F14FDF88CFB1                1.00                   1.0

[1920 rows x 2 columns]

In [ ]:
# gas list

In [22]:
# gas_st_list = list(data.groupby('Карта').mean()['АЗСКод'].astype(int).unique())

In [23]:
# card_data = pd.concat([card_data, data.groupby('Карта').mean()['АЗСКод'].apply(lambda x:gas_st_list.index(x))], axis=1)

In [49]:
data

,ДатаЧека,НомерЧека,ВидОперации,АЗСКод,ВидНоменклатуры,Карта,ОсновнаяКарта,НомерСтроки,НоменклатураКод,Количество,Цена,Сумма,Бонусы,СуммаСкидки,УниверсальнаяАкцияКод,СписаноБонусов,СуммаСкидкиДисконт,КассоваяСмена,ОператорКод,ДатаЧека_m
30,03.06.2020,34224000001083,Начисление,3422,Нефтепродукты,35EA47FAEA5B9DF549024C81E6A5FCA8,NaN,1,153243.0,20.00,24.49,489.80,4700.0,0.00,0.0,0.0,0,921923d6-a514-11ea-95f8-00012eb194d9,Булименко Тетяна Миколаївна,06
31,03.06.2020,34224000001092,Начисление,3422,Нефтепродукты,53B701B8794F74109D19A0DACE19D1FF,NaN,1,2865.0,8.72,11.48,100.00,100.0,0.11,0.0,0.0,0,921923d6-a514-11ea-95f8-00012eb194d9,Булименко Тетяна Миколаївна,06
39,03.06.2020,34224000001130,Начисление оплата,3422,Нефтепродукты,711F10D4E2AC89E957B4228C414DAEA7,NaN,1,2856.0,30.00,24.49,734.00,7042.0,0.70,0.0,70.0,0,921923d6-a514-11ea-95f8-00012eb194d9,Булименко Тетяна Миколаївна,06
40,03.06.2020,26201000001190,Начисление,2620,Нефтепродукты,7BDB370531D6DC2E698B32FD3CC99763,NaN,1,145236.0,10.01,23.49,235.00,3504.0,0.13,224.0,0.0,0,54519072-a514-11ea-afbd-00012eb19ff4,Шведюк Іван Михайлович,06
50,03.06.2020,34224000001161,Начисление,3422,Нефтепродукты,6C92B81432E32A05374C6A1F0FAF094D,NaN,1,2865.0,16.36,11.48,187.81,818.0,0.00,0.0,0.0,0,921923d6-a514-11ea-95f8-00012eb194d9,Булименко Тетяна Миколаївна,06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19459,04.05.2020,26201000002123,Начисление,2620,Нефтепродукты,71557CEEA393407549118FF4FA91EAB3,NaN,1,113355.0,12.51,23.99,300.00,1876.0,0.11,0.0,0.0,0,60ae5d74-8d81-11ea-afb5-00012eb19ff4,Соболь Наталія Михайлівна,05
19464,04.05.2020,16461000001837,Начисление,1646,Нефтепродукты,B1B3A892578C48C7723DC06F9F7ACE4B,NaN,1,145236.0,10.00,23.99,239.90,1500.0,0.00,0.0,0.0,0,08147650-8d82-11ea-8a21-00012eb1a3b4,Марчук Альона Ігорівна,05
19465,04.05.2020,34224000001735,Начисление оплата,3422,Нефтепродукты,E10C67A7065BF1AEDD0C6CB4FE9C4CAA,NaN,1,2856.0,20.00,24.99,499.00,3994.0,0.80,0.0,80.0,0,0ecfc5f5-8d82-11ea-95ed-00012eb194d9,Булименко Тетяна Миколаївна,05
19467,04.05.2020,16461000001867,Начисление оплата,1646,Нефтепродукты,B1B3A892578C48C7723DC06F9F7ACE4B,NaN,1,145236.0,20.00,23.99,0.20,0.0,479.60,0.0,47980.0,0,08147650-8d82-11ea-8a21-00012eb1a3b4,Марчук Альона Ігорівна,05
19469,04.05.2020,16461000001872,Начисление,1646,Нефтепродукты,B1B3A892578C48C7723DC06F9F7ACE4B,NaN,1,113355.0,12.51,23.99,300.11,1876.0,0.00,0.0,0.0,0,08147650-8d82-11ea-8a21-00012eb1a3b4,Марчук Альона Ігорівна,05

In [48]:
data.groupby('Карта').mean()

,НомерЧека,АЗСКод,НомерСтроки,НоменклатураКод,Количество,Цена,Сумма,Бонусы,СуммаСкидки,УниверсальнаяАкцияКод,СписаноБонусов,СуммаСкидкиДисконт
Карта,,,,,,,,,,,,
0357098A9B4792A725030975FF992E46,2.620100e+13,2620.0,1.0,141710.000000,18.651111,24.434444,369.393333,4099.888889,87.063333,0.000000,8709.888889,0.0
03A32DA0336671361C853C10B69E95AF,2.620100e+13,2620.0,1.0,145236.000000,10.712000,23.956667,256.636667,1631.533333,0.097333,14.933333,0.000000,0.0
07D3E77CD24DA3154BA219D09BF93B4B,2.620100e+13,2620.0,1.0,72147.600000,4.525200,25.826000,114.406200,256.020000,2.904400,0.000000,287.660000,0.0
0847BF2B4784F83823D515D04C6D9639,2.620100e+13,2620.0,1.0,145236.000000,8.315000,23.990000,200.020000,1518.166667,0.013333,0.000000,0.000000,0.0
0B1FF492733C3A08D34DE0D7424A2549,2.620100e+13,2620.0,1.0,134689.333333,3.884074,23.964074,92.977037,92.740741,0.028148,0.000000,0.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
E762D39C0AD2B8E8F25FCF4652E65689,2.620100e+13,2620.0,1.0,72864.272727,20.041364,21.578636,373.190455,3739.772727,28.846364,0.000000,2884.227273,0.0
EAA77BE5D715CF896BEB26C0674F7024,2.620100e+13,2620.0,1.0,85364.478261,7.966522,23.528261,186.182174,976.217391,0.008696,0.000000,0.000000,0.0
EBF4E943181ADB99FEB3A30A7101562B,3.422400e+13,3422.0,1.0,2863.650000,17.704000,12.931500,181.608000,350.000000,33.660000,3.000000,0.000000,0.0
F125B1B2BBF74755ACA2537AAA209E7C,3.422400e+13,3422.0,1.0,23664.315789,8.881053,16.652632,137.103158,451.052632,0.042105,0.000000,0.000000,0.0
F5D40EB63F272F3425457352C9168C9F,2.620100e+13,2620.0,1.0,23842.357143,24.040000,24.060714,530.061429,5102.428571,40.532143,0.000000,4049.500000,0.0

In [ ]:
# operations per day

In [35]:
mean_list = []
for i in list(data.groupby('Карта').count().index):
    mean_oper = np.mean(list(data[data['Карта'] == i].groupby('ДатаЧека').count()['ВидОперации']))
    mean_list.append(round(mean_oper, 2))

In [36]:
card_data['operations_per_day'] = mean_list

In [ ]:
# special_discounts

In [185]:
list_3 = []
list_224 = []
for i in list(final_card_data.index):
    data_list = list(data[data['Карта'] == i]['УниверсальнаяАкцияКод'])
    list_3.append(data_list.count(3.0))
    list_224.append(data_list.count(224.0))

In [186]:
final_card_data['special_discount_3'] = list_3
final_card_data['special_discount_224'] = list_224

In [187]:
final_card_data

,operations_per_day,operations_per_month,special_discount_3,special_discount_224
Карта,,,,
002043206DC69131FC6444B0880F2D07,1.00,1.0,0,0
0049F1FFC58BD9977F50E56C71D5536B,1.50,1.0,0,0
005595BFFC7222DBB557E59A3872E56D,1.71,1.0,7,0
00DC9FCD81231002E2015CF04A2B01C2,1.00,1.0,11,0
00EB869662094C3C148EAEB8672D2BB7,1.75,1.0,7,0
...,...,...,...,...
FF88E8952CBA6FF330B9DF3F6CA6F2DA,1.00,1.0,0,0
FFB1A367E4B62FB268767E712E404986,1.60,1.0,5,0
FFD689128D88650F6820A54E3604DD09,1.60,1.0,0,0
FFD8567FF1048ABD2B486C2D08FE3B34,1.78,1.0,0,0
FFDDE5951E14CA31FA92F14FDF88CFB1,1.00,1.0,0,0

In [ ]:
# bonuses

In [188]:
final_card_data = pd.concat([final_card_data, data.groupby('Карта').mean()[['Сумма', 'Бонусы', 'СуммаСкидки', 'СписаноБонусов']].apply(lambda x: round(x, 2))], axis=1)

In [ ]:
# ВидОперации, ОператорКод

In [74]:
oper_type = []
for i in list(final_card_data.index):
    xx = data[data['Карта'] == i].groupby('ВидОперации').count()
    try:
        oper_type.append(round(xx.loc['Начисление оплата']['ДатаЧека']/xx.loc['Начисление']['ДатаЧека'], 2))
    except:
        oper_type.append(0.5)

In [76]:
final_card_data['oper_type'] = oper_type

In [189]:
final_card_data

,operations_per_day,operations_per_month,special_discount_3,special_discount_224,Сумма,Бонусы,СуммаСкидки,СписаноБонусов
Карта,,,,,,,,
002043206DC69131FC6444B0880F2D07,1.00,1.0,0,0,800.00,5372.00,83.46,8345.00
0049F1FFC58BD9977F50E56C71D5536B,1.50,1.0,0,0,259.69,965.17,0.04,0.00
005595BFFC7222DBB557E59A3872E56D,1.71,1.0,7,0,326.86,2463.14,25.27,1630.57
00DC9FCD81231002E2015CF04A2B01C2,1.00,1.0,11,0,790.27,5300.55,83.30,5490.00
00EB869662094C3C148EAEB8672D2BB7,1.75,1.0,7,0,510.04,3717.62,18.70,0.00
...,...,...,...,...,...,...,...,...
FF88E8952CBA6FF330B9DF3F6CA6F2DA,1.00,1.0,0,0,352.13,1306.40,0.03,0.00
FFB1A367E4B62FB268767E712E404986,1.60,1.0,5,0,853.26,0.00,98.42,0.00
FFD689128D88650F6820A54E3604DD09,1.60,1.0,0,0,305.22,1543.40,64.25,6426.40
FFD8567FF1048ABD2B486C2D08FE3B34,1.78,1.0,0,0,400.09,2093.44,59.58,5957.67
FFDDE5951E14CA31FA92F14FDF88CFB1,1.00,1.0,0,0,251.79,1054.62,0.14,14.38

In [146]:
i_data = data[data['Карта'] == 'F5D40EB63F272F3425457352C9168C9F']
max_day = max(i_data.groupby('ДатаЧека').count()['НомерЧека'])
max_mon = max(i_data.groupby('ДатаЧека_m').count()['НомерЧека'])
len_oper = len(i_data)
len_d = len(set(i_data['ДатаЧека']))
len_m = len(set(i_data['ДатаЧека_m']))
mean_day = len_oper/len_d
mean_mon = len_oper/len_m

In [147]:
max_day

1

In [151]:
i_data.groupby('ДатаЧека_m').count()['НомерЧека']

ДатаЧека_m
05    2
06    6
07    5
08    1
Name: НомерЧека, dtype: int64

In [152]:
mean_mon

3.5

In [ ]:
sum(list(data[data['Карта'] == 'F9CF1DC89C51CEC7AADC699E41D3B5FA'].groupby('ДатаЧека').count()['ВидОперации']))

In [ ]:
np.mean(list(data[data['Карта'] == 'D85BD7BDD888729BA02B98F56DD71B28'].groupby('ДатаЧека').count()['ВидОперации']))

In [ ]:
data

In [ ]:
data[data['Карта'] == 'F9CF1DC89C51CEC7AADC699E41D3B5FA'].iloc[0]['ДатаЧека'].split(' ')[0]

In [ ]:
fraud_list = []
for i in labels:
    fraud_list.append(i[0])

In [ ]:
len(fraud_list)

In [ ]:
l_0 = []
l_1 = []

In [ ]:
for i in list(data.groupby('Карта').count().index):
    oper_len = np.mean(list(data[data['Карта'] == i].groupby('ДатаЧека').count()['ВидОперации']))
    print(oper_len)
    break

In [ ]:
len(l_0)

In [ ]:
print(np.mean(l_0))
print(np.median(l_0))
print(stats.mode(l_0))

In [ ]:
print(np.mean(l_1))
print(np.median(l_1))
print(stats.mode(l_1))

In [ ]:
len(l_1)

In [ ]:
data.loc[data['Карта'] == '002043206DC69131FC6444B0880F2D07'].groupby('ОператорКод').count()

In [ ]:
for i in labels:
    print(i)
    data.loc[data['Карта'] == i[0]].groupby('ОператорКод').count()
    break

In [ ]:
data.loc[data['Карта'] == 'E1627DA6992F9BD6D6F10EF15B3930F6'].groupby('ОператорКод').count()

In [ ]:
data.loc[data['label']==1].groupby('Карта').count()

In [ ]:
data.loc[data['label']==1].groupby('АЗСКод').count()

In [ ]:
data.loc[data['label']==1].loc[data['Карта']=='00DC9FCD81231002E2015CF04A2B01C2']

In [ ]:
labels[1][0]

In [ ]:
for i in labels:
    x = data.loc[data['Карта']==i[0]]['АЗСКод'].values
    print(x)
    break

In [ ]:
xx = data.loc[data['label']!=1]['Карта'].values

In [ ]:
many_st = []
for i in set(data['Карта'].values):
    if len(set(data.loc[data['Карта']==i]['АЗСКод'].values)) > 1: 
        many_st.append(i)

In [ ]:
many_st = []

In [ ]:
len(many_st)

In [ ]:
yy = data.loc[data['label']==1]['Карта'].values

In [ ]:
for i in set(yy):
    x = data.loc[data['Карта']==i]['АЗСКод'].values
    if len(set(x)) == 1: 
        sfsdf.append(i)

In [ ]:
len(sfsdf)

In [ ]:
data[data['УниверсальнаяАкцияКод']==224.0].loc[data['label']==1]

In [ ]:
data['УниверсальнаяАкцияКод'] = data['УниверсальнаяАкцияКод'].fillna(0)

In [ ]:
data['УниверсальнаяАкцияКод']

In [ ]:
card_data = data.groupby('Карта').count()

In [ ]:
card_data = card_data[card_data['ДатаЧека']<5]

In [ ]:
card_list = list(card_data[card_data['ДатаЧека']>10].index)
counter = 0
for i in labels:
    if i[0] in card_list:
        counter += 1
print(counter)

In [ ]:
delete_list = card_data[card_data['ДатаЧека']<5].index

In [ ]:
for i in delete_list:
    data = data[data['Карта'] != i]

In [ ]:
len(data)

In [ ]:
data.loc[data['label']==1].groupby('УниверсальнаяАкцияКод').count()

In [ ]:
data.loc[data['label']!=1].groupby('УниверсальнаяАкцияКод').count()

In [ ]:
data = data[data['УниверсальнаяАкцияКод'] < 300]

In [ ]:
data[data['УниверсальнаяАкцияКод'] < 300].groupby('Карта').count()

In [ ]:
data

In [ ]:
# remove column
# data = data.drop('ДатаЧека', axis=1)

In [ ]:
data = data.drop('НомерЧека', axis=1)
data = data.drop('ОсновнаяКарта', axis=1)
data = data.drop('НомерСтроки', axis=1)
data = data.drop('НоменклатураКод', axis=1)

In [ ]:
# filtering rows
data = data[data['ВидНоменклатуры']=='Нефтепродукты']

# removing the column
data = data.drop('ВидНоменклатуры', axis=1)

##### "ВидОперации"

In [ ]:
# filtering rows
data = data[data['ВидОперации']!='Начисление возврат']
data = data[data['ВидОперации']!='Начисление оплата возврат']

In [ ]:
# normalize data for learning

# making list with names
# list_names = list(data['ВидОперации'].unique())

# replacing string with [0,1]
# data['ВидОперации'] = data['ВидОперации'].apply(lambda x:list_names.index(x))

# removing the column
data = data.drop('ВидОперации', axis=1)

In [ ]:
data.groupby('АЗСКод').count()

In [ ]:
data.loc[data['label']==1].groupby('АЗСКод').count()

##### "АЗСКод"

In [ ]:
# checking unique values
list(data['АЗСКод'].unique())

In [ ]:
# normalize data for learning

# making list with names
list_stations = list(data['АЗСКод'].unique())

# replacing string with [0,1,..]
data['АЗСКод'] = data['АЗСКод'].apply(lambda x:list_stations.index(x))

##### "ВидНоменклатуры"

Most fraud cases happen with Gas purchasing, so we will leave only 'Нефтепродукты' rows and remove the entire column

In [ ]:
# filtering rows
data = data[data['ВидНоменклатуры']=='Нефтепродукты']

# removing the column
# data = data.drop('ВидНоменклатуры', axis=1)

##### "Карта"

In [ ]:
# checking quantity of unique cards 
data['Карта'].describe()

Only 20259 cards used among 47384 operations, this means that some cards were used several times.

Obviously a card number doesn't provide model with any useful information, we will replace the values with numbers of usage frequency for the card.

In [ ]:
# grouping by cards
count_card = data.groupby('Карта').count()

#### *bonus

Checking the most frequently used card

In [ ]:
# filter card with more than 100 operations
count_card[count_card['ВидОперации']>=100]

In [ ]:
# showing operations with this card only
card_data = data[data['Карта']=='3A68C9A32E07603A1D5EA7CE1A800EB6']

# grouping by operations quantity per operator 
card_data.groupby('ОператорКод').count()

In [ ]:
# visualizing result
pie_gr = card_data.groupby('ОператорКод').count()
plt.pie(pie_gr['ВидОперации'], labels=pie_gr.index, autopct=lambda pct: int(119*pct/100))
plt.show()

As we can see only one operator "Фера Радміла Іванівна" has done 101 operations with the same card

In [ ]:
# replacing the values with numbers of usage frequency
data['Карта'] = data['Карта'].apply(lambda x:count_card.loc[x]['ВидОперации'])

In [ ]:
data = data.drop('ОсновнаяКарта', axis=1)

##### "НомерСтроки"

We will drop this info as it's not important for the model

In [ ]:
data = data.drop('НомерСтроки', axis=1)

##### "НоменклатураКод"

We will drop this column as we know that there are only gas products

In [ ]:
data = data.drop('НоменклатураКод', axis=1)

##### "Количество", "Цена", "Сумма", "Бонусы", "СуммаСкидки"

These columns we will leave unchanged, just need to convert string into float number

In [ ]:
# converting string values to float
data['Количество'] = data['Количество'].apply(lambda x:float(x.replace('\xa0', '').replace(',', '.')))
data['Цена'] = data['Цена'].apply(lambda x:float(x.replace('\xa0', '').replace(',', '.')))
data['Сумма'] = data['Сумма'].apply(lambda x:float(x.replace('\xa0', '').replace(',', '.')))
data['Бонусы'] = data['Бонусы'].apply(lambda x:float(x.replace('\xa0', '').replace(',', '.')))
data['СуммаСкидки'] = data['СуммаСкидки'].apply(lambda x:float(x.replace('\xa0', '').replace(',', '.')))

##### "УниверсальнаяАкцияКод"

In [ ]:
# checking unique values
list(data['УниверсальнаяАкцияКод'].unique())

In [ ]:
# replace NaN values
data['УниверсальнаяАкцияКод'] = data['УниверсальнаяАкцияКод'].fillna(0)

In [ ]:
# normalize data for learning

# making list with names
list_disc_types = list(data['УниверсальнаяАкцияКод'].unique())

# replacing string with [0,1,..]
data['УниверсальнаяАкцияКод'] = data['УниверсальнаяАкцияКод'].apply(lambda x:list_disc_types.index(x))

##### "СписаноБонусов"

We will leave this unchanged

In [ ]:
# converting unicode string to integer
data['СписаноБонусов'] = data['СписаноБонусов'].apply(lambda x:int(x.replace('\xa0', '')))

##### "СуммаСкидкиДисконт"

In [ ]:
# checking for unique values
data['СуммаСкидкиДисконт'].unique()

This column has only 0 values, we will drop it

In [ ]:
data = data.drop('СуммаСкидкиДисконт', axis=1)

##### "КассоваяСмена"

This values will not help model, let's drop it

In [ ]:
data = data.drop('КассоваяСмена', axis=1)

##### "ОператорКод"

In [ ]:
# checking for unique values
data['ОператорКод'].unique()

In [ ]:
# normalize data for learning

# making list with names
list_operators = list(data['ОператорКод'].unique())

# replacing string with [0,1,..]
data['ОператорКод'] = data['ОператорКод'].apply(lambda x:list_operators.index(x))

Also dropping the last useless column 'Unnamed: 19'

In [ ]:
data = data.drop('Unnamed: 19', axis=1)

##### Normalized dataset for learning model

In [ ]:
data.head(10)

### Training model

In [ ]:
# importing IsolationForest Algorithm
from sklearn.ensemble import IsolationForest

In [ ]:
# creating model
clf = IsolationForest(random_state=0)

In [ ]:
# fit model
clf.fit(data.values)

### Predicting and analyzing result

In [ ]:
# making prediction on the dataset
prediction = clf.predict(data.values)

In [ ]:
# replace 1 for inliers, -1 for outliers with 0 for inliers and 1 for outliers
anomaly = np.where(prediction==-1, 1, 0)

In [ ]:
# adding column to data frame
data['Anomaly'] = anomaly

In [ ]:
# showing result
data.head(10)

In [ ]:
# filter data only for anomaly operations
anomaly_data = data[data['Anomaly']==1]

In [ ]:
# sorting by operator with the highest anomaly operations
anomaly_sorted = anomaly_data.groupby('ОператорКод').count().sort_values('Anomaly', ascending=False)

In [ ]:
# visualizing result
plt.scatter(anomaly_sorted.index, anomaly_sorted['Anomaly'])
plt.plot([0,60], [230,230], color='red')
plt.show()

We can clearly see that in most cases anomaly frequency is below 230, only few are more than that

Let's filter only those operators who are above the line

In [ ]:
# sort only for the highest frequency
anomaly_sorted = anomaly_sorted[anomaly_sorted['Anomaly']>230]
anomaly_sorted

In [ ]:
# getting list of operators names
names = []
for name_index in list(anomaly_sorted.index):
    names.append(list_operators[name_index])

In [ ]:
# getting list of anomaly quantity
cases = list(anomaly_sorted['Anomaly'].values)

In [ ]:
# making dataframe
anomaly_list = pd.DataFrame(data={'Operator':names, 'Anomaly operations':cases})

#### Result

In [ ]:
# showing dataframe
anomaly_list

In [ ]:
labels = pd.read_csv('other_data/card_69.csv').values

In [ ]:
'294408237E2B9930B593D42E92C500DA' in labels

In [ ]:
labels

In [ ]:
for i, row in data

In [ ]:
test_data = card_data.drop('is_fraud', axis=1)

In [ ]:
test_data.values

In [ ]:
clf.fit(test_data.values)

In [ ]:
prediction = clf.predict(test_data.values)

In [ ]:
anomaly = np.where(prediction==-1, 1, 0)

In [ ]:
test_pred = pd.DataFrame(card_data['is_fraud'])

In [ ]:
test_pred['predicted'] = anomaly

In [ ]:
x = test_pred[test_pred['is_fraud'] == test_pred['predicted']]

In [ ]:
len(x[x['is_fraud'] == 1])

In [ ]:
card_data = card_data[:1946]

In [ ]:
test_pred

In [ ]:
from sklearn.cluster import KMeans

In [ ]:
kmeans = KMeans(n_clusters=2, random_state=0).fit(test_data.values)

In [ ]:
y = list(kmeans.predict(test_data.values))

In [ ]:
y.count(0)

In [ ]:
test_pred['predicted'] = y

In [217]:
# machine learning
from sklearn.svm import SVC, LinearSVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import GradientBoostingClassifier

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [163]:
final_data_test = final_card_data.copy()

In [255]:
final_data_test.to_csv('test.csv')

In [256]:
final_card_data.to_csv('train.csv')

In [209]:
train_X = final_card_data.drop('is_fraud', axis=1).values

In [210]:
train_y = final_card_data['is_fraud'].values

In [213]:
train_y.shape

(1920,)

In [214]:
test_X = final_data_test.values

In [216]:
test_X.shape

(101, 7)

In [238]:
rfc = RandomForestClassifier(n_estimators=1000)
rfc.fit(train_X, train_y)

RandomForestClassifier(n_estimators=1000)

In [239]:
y_pred = rfc.predict(train_X)

In [240]:
print(classification_report(train_y, y_pred))
print('-'*50)
print('Confusion Matrix')
print(confusion_matrix(train_y, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1854
           1       1.00      1.00      1.00        66

    accuracy                           1.00      1920
   macro avg       1.00      1.00      1.00      1920
weighted avg       1.00      1.00      1.00      1920

--------------------------------------------------
Confusion Matrix
[[1854    0]
 [   0   66]]

In [241]:
res = rfc.predict(test_X)

In [242]:
res

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [244]:
gbc = GradientBoostingClassifier(n_estimators=100, max_depth=1, random_state=0)
gbc.fit(train_X, train_y)

GradientBoostingClassifier(max_depth=1, random_state=0)

In [248]:
y_pred = gbc.predict(train_X)

In [249]:
print(classification_report(train_y, y_pred))
print('-'*50)
print(confusion_matrix(train_y, y_pred))

              precision    recall  f1-score   support

           0       0.98      1.00      0.99      1854
           1       1.00      0.29      0.45        66

    accuracy                           0.98      1920
   macro avg       0.99      0.64      0.72      1920
weighted avg       0.98      0.98      0.97      1920

--------------------------------------------------
[[1854    0]
 [  47   19]]

In [250]:
res = gbc.predict(test_X)

In [251]:
res

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [253]:
np.save(np.array(train_X), 'train_x.npy')

TypeError: expected str, bytes or os.PathLike object, not numpy.ndarray

In [254]:
train_X

array([[1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 5.37200e+03,
        8.34600e+01, 8.34500e+03],
       [1.50000e+00, 0.00000e+00, 0.00000e+00, ..., 9.65170e+02,
        4.00000e-02, 0.00000e+00],
       [1.71000e+00, 7.00000e+00, 0.00000e+00, ..., 2.46314e+03,
        2.52700e+01, 1.63057e+03],
       ...,
       [1.60000e+00, 0.00000e+00, 0.00000e+00, ..., 1.54340e+03,
        6.42500e+01, 6.42640e+03],
       [1.78000e+00, 0.00000e+00, 0.00000e+00, ..., 2.09344e+03,
        5.95800e+01, 5.95767e+03],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.05462e+03,
        1.40000e-01, 1.43800e+01]])